import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const videoLink = "/mov_bbb.mp4";
  const handleClick = (e) => {
    console.log(e.target)
    const { currentTime, paused, seeking, duration, defaultMuted, ended, loop, volume, autofocus } = e.target;
    console.log({ currentTime, paused, seeking, duration, defaultMuted, ended, loop, volume, autofocus })
  }
  return (
    <>
      <Head>
        <title>Custom video player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      </main>
    </>
  )
}
