import { Inter } from '@next/font/google';
import Head from 'next/head';
import { Video } from '../components/video';
import styles from '../styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });
export default function Home() {
    const videoLink = '/mov_bbb.mp4';
    const handleClick = (e) => {
        console.log(e.target);
        const {
            currentTime,
            paused,
            seeking,
            duration,
            defaultMuted,
            ended,
            loop,
            volume,
            autofocus,
        } = e.target;
        console.log({
            currentTime,
            paused,
            seeking,
            duration,
            defaultMuted,
            ended,
            loop,
            volume,
            autofocus,
        });
    };
    return (
        <>
            <Head>
                <title>Custom video player</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='text-center font-bold mt-10'>
                Mohammad Shahjalal
                <br />
                Software Engineer
                <br />
                TechnoNext Ltd. a sister concern of US Bangla Group
                <br />
                +8801612233903
                <br />
                shahjalal.csegub@gmail.com
            </div>
            <main className={styles.main}>
                <div>
                    <Video src={'https://media.w3.org/2010/05/sintel/trailer_hd.mp4'} />
                    <Video
                        src={
                            'http://tecfa.unige.ch/guides/html/html5-video/videos/state-of-wikipedia-480x272.mp4'
                        }
                    />
                </div>
            </main>
        </>
    );
}
