import { Inter } from '@next/font/google';
import Head from 'next/head';
import { Video } from '../components/video';
import styles from '../styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });
export default function Home() {
    const videoLink = '/mov_bbb.mp4';
    const handleClick = (e) => {
        console.log(e.target);
        const {
            currentTime,
            paused,
            seeking,
            duration,
            defaultMuted,
            ended,
            loop,
            volume,
            autofocus,
        } = e.target;
        console.log({
            currentTime,
            paused,
            seeking,
            duration,
            defaultMuted,
            ended,
            loop,
            volume,
            autofocus,
        });
    };
    return (
        <>
            <Head>
                <title>Custom video player</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                {/* <div > <h1 className="text-3xl font-bold bg-red-400"> Hello world! </h1> </div> <video controls autoPlay loop onClick={(e) => handleClick(e)} > <source src={videoLink} /> </video> <video src="https://res.cloudinary.com/dssvrf9oz/video/upload/v1635662987/pexels-pavel-danilyuk-5359634_1_gmixla.mp4"> </video> */}
                <div>
                    <Video src='https://res.cloudinary.com/aremusmog/video/upload/v1668090866/WeTube/TRAILER_qurlei.mp4' />
                </div>
            </main>
        </>
    );
}
